# Generated by Django 3.0.6 on 2020-05-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgModel',
        ),
    ]
